# Generated by Django 3.2.6 on 2021-08-19 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('text', models.TextField(max_length=1024)),
                ('attack', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('abbr', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('SUPER_RARE', 'Super Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('SECRET_RARE', 'Secret Rare')], default='COMMON', max_length=32)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='cards.cardset')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardattribute'),
        ),
        migrations.AddField(
            model_name='card',
            name='releases',
            field=models.ManyToManyField(related_name='cards', through='cards.Release', to='cards.CardSet'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardtype'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('set_id', 'card_id'), name='unique card/set'),
        ),
    ]
