# Generated by Django 3.2.6 on 2021-08-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardset',
            old_name='full_name',
            new_name='name',
        ),
    ]
