# Generated by Django 3.2.6 on 2021-10-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210823_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attribute',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='CardAttribute',
        ),
        migrations.DeleteModel(
            name='CardType',
        ),
    ]
